# Generated by Django 5.2.8 on 2025-11-28 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GERENTE', 'Gerente'), ('DESENVOLVEDOR', 'Desenvolvedor'), ('STAKEHOLDER', 'Stakeholder'), ('TESTER', 'Tester')], max_length=20),
        ),
    ]
