# Generated by Django 5.2.9 on 2025-12-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=15),
            preserve_default=False,
        ),
    ]
