# Generated by Django 5.2.8 on 2025-11-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil_telefone_alter_perfil_tipo'),
    ]

    operations = [
    ]
